app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/***************    Front End   ***********************/
Route::get('/', 'FrontEndController@index');
Route::get('/home', 'FrontEndController@index');
Route::get('/portfolio', 'FrontEndController@getPortfolio');
Route::get('/news', 'FrontEndController@getNews');
Route::get('/news/{id}', 'FrontEndController@getSingleNews');
Route::get('/artists', 'FrontEndController@getAllArtists');
Route::get('/dashboard', 'DashboardController@index');

/****************** Ajax Queries (JSON)**************************************/
Route::get('/getCategories', 'ArtCategoryController@getAllArtCategory');
Route::get('/getPhotos', 'PhotoController@getPhotosByCategoryNArtist');
Route::get('/getArtists', 'PortfolioController@getArtistsByCategoryNArtist');
Route::get('/searchArtistByAlphabet', 'PortfolioController@searchArtistByAlphabet');
Route::get('/getSliderImages', 'SliderController@getSliderImages');
Route::get('/getArtistPhotos', 'PhotoController@getArtistPhotos');
Route::get('/getAllArtists', 'PortfolioController@getAllArtist');
Route::post('/contactus', 'FrontEndController@contactUs');

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);





Route::group(['middleware' => 'admin'], function () {

    /**************** Slider **************************/
    Route::resource('sliders', 'SliderController');

    /**************** Dynamic Contents **************************/
    Route::resource('dynamiccontents', 'DynamicContentController',['except' => 'show']);

    /**************** Album **************************/
    Route::resource('albums', 'AlbumController');


    /**************** Photos ************************/
    Route::resource('photos', 'PhotoController',['except' => 'show']);
    Route::get('photo-album/{albumID}/{page?}', 'PhotoController@getPhotosByAlbum');


    /*************** Portfolios *******************/
    Route::resource('portfolios', 'PortfolioController');
    Route::post('updateProfile', ['as'=>'updateProfile','uses' =>'PortfolioController@updateProfile'] );



    /*************** ArtCategories ***************/
    Route::resource('artcategories', 'ArtCategoryController');


    /*************** Article ************************/
    Route::resource('articles', 'ArticleController',['except' => 'show']);


    /*************** EducationHistory ************************/
    Route::resource('education', 'EducationHistoryController');


    /*************** Awardhistroy ************************/
    Route::resource('awardhistories', 'AwardHistoryController');

    /*************** Exhibition ************************/
    Route::resource('exhibition', 'ExhibitionController');

    /*************** UserController ************************/
    Route::resource('users', 'UserController', ['except' => 'show']);

    Route::get('userstatus/{id}/{status}', 'UserController@changeStatus');


});
Route::resource('dynamiccontents', 'DynamicContentController',['only' => 'show']);
Route::resource('articles', 'ArticleController',['only' => 'show']);
Route::resource('photos', 'PhotoController', ['only' => 'show']);
Route::resource('users', 'UserController', ['only' => 'show']);

app/Exhibition.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;
/**
 * Class Exhibition
 * @package App
 */
class Exhibition extends Model {

    protected $guarded = [];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function portfolio(){
        return $this->belongsTo('App\Portfolio');
    }

    /**
     * @param bool $excludeDeleted
     * @return $this
     */
    public function newQuery($excludeDeleted = true)
    {
        $query = parent::newQuery($excludeDeleted);
        if(Auth::check() && (!Auth::user()->hasRole('admin')))
            return $query->where('portfolio_id', Auth::user()->profile->id);
        else
            return $query;
    }
}

app/Http/Controllers/ExhibitionController.php
<?php namespace App\Http\Controllers;

use App\Portfolio;
use App\Repository\ExhibitionRepository as Exhibition;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Http\Requests\CreateExhibitionRequest;
use Request;
use Session;

class ExhibitionController extends Controller
{

    /**
     * @var int
     */
    private $count;

    /*
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

        $this->count = 10;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Exhibition $exhibition
     * @return Response
     */
    public function index(Exhibition $exhibition)
    {

        $exhibitions = $exhibition->paginate($this->count);

        return view('admin.exhibitions.index', compact('exhibitions'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create(Portfolio $portfolio)
    {
        return view('admin.exhibitions.create')->with('portfolios', $portfolio->all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateExhibitionRequest $request
     *
     * @return Response
     */

    public function store(CreateExhibitionRequest $request, Exhibition $exhibition)
    {
        $exhibition->create($request->all());
        Session::flash('message', 'The Exhibition was successfully added!.');
        Session::flash('flash_type', 'alert-success');

        return redirect('exhibition');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id, Exhibition $exhibition, Portfolio $portfolio)
    {

        return view('admin.exhibitions.edit')->with('exhibition', $exhibition->find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id, CreateExhibitionRequest $request, Exhibition $exhibition)
    {
        $exhibition->find($id)->update($request->all());
        Session::flash('message', 'The Exhibition was successfully added!.');
        Session::flash('flash_type', 'alert-success');

        return redirect('exhibition');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }

    public function getAllExhibition(Exhibition $exhibition)
    {
        return \response::json($exhibition->all());
    }
}

resources/views/admin/exhibitions/create.blade.php
@extends('admin')

@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Add Exhibition</h3>
    </div>
@stop

@section('adminContent')
    <div class = "article-content">
                        {!! Form::open(['route'=>'exhibition.store'])!!}

                            <fieldset>
                                 <div class="form-group">
                                     <label><b>TITLE</b></label>
                                     {!! Form::text('title',null,array('class'=>'form-control')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>DESCRIPTIOIN</b></label>
                                     {!! Form::textarea('description',null,array('class'=>'form-control')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>YEAR</b></label>
                                     {!! Form::text('year',null,array('class'=>'form-control')) !!}
                                 </div>
                                <div class="form-group">
                                    <label>USER</label>
                                    {!! Form::select('portfolio_id', $portfolioLists) !!}
                                </div>
                                <center>{!! form::submit('Add',[' class'=>'btn btn-primary form-control'])!!}</center>

                            </fieldset>
                        {!! Form::close()!!}
                    </div>

@stop

resources/views/admin/exhibitions/edit.blade.php
@extends('admin')

@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Edit Exhibition</h3>
    </div>
@stop

@section('adminContent')
    <div class = "portfolio-content">
                         {!! Form::model($exhibition,array('method' => 'PATCH','route'=>array('exhibition.update',$exhibition->id))) !!}

                            <fieldset>
                                 <div class="form-group">
                                     <label><b>TITLE</b></label>
                                     {!! Form::text('title',null,array('class'=>'form-control')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>DESCRIPTIOIN</b></label>
                                     {!! Form::textarea('description',null,array('class'=>'form-control')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>YEAR</b></label>
                                     {!! Form::text('year',null,array('class'=>'form-control')) !!}
                                 </div>
                                <div class="form-group">
                                    <label>USER</label>
                                    {!! Form::select('portfolio_id', $portfolioLists) !!}
                                </div>
                                {!! form::submit('Update',[' class'=>'btn btn-primary form-control'])!!}

                            </fieldset>
                        {!! Form::close()!!}
                    </div>
                </div>

        </div>
    </div>
</div><!-- /col-lg-9 END SECTION MIDDLE -->
@stop

resources/views/admin/exhibitions/index.blade.php
@extends('admin')

@section('breadcrumb')
    <h3 class="panel-title">Exhibition</h3>

    <div class="sub-menu">
        <a href="{{url('exhibition/create')}}"><i class="fa fa-plus-circle fa-2x pull-right"></i></a>

    </div>
@stop

@section('adminContent')
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
            <th> ID</th>
            <th> TITLE</th>
            <th> DESCRIPTION</th>
            <th> YEAR</th>
            <th> NAME</th>
            <th> EDIT</th>
            </thead>

            <tbody>

                @foreach($exhibitions as $exhibition)
                    <tr>
                    <td>{!! $exhibition->id!!}</td>
                    <td>{!! $exhibition->title !!}</td>
                    <td>{!! $exhibition->description !!}</td>
                    <td>{!! $exhibition->year !!}</td>
                    <td>{!! $exhibition->portfolio->first_name!!}</td>
                    <td>{!! link_to_route('exhibition.edit', '', array($exhibition->id),array('class' => 'fa fa-pencil fa-fw')) !!}</td>
                @endforeach
            </tr>
            </tbody>
        </table>
        <div class="pagination"> {!! $exhibitions->render() !!} </div>
    </div>
@stop