app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/***************    Front End   ***********************/
Route::get('/', 'FrontEndController@index');
Route::get('/home', 'FrontEndController@index');
Route::get('/portfolio', 'FrontEndController@getPortfolio');
Route::get('/news', 'FrontEndController@getNews');
Route::get('/news/{id}', 'FrontEndController@getSingleNews');
Route::get('/artists', 'FrontEndController@getAllArtists');
Route::get('/dashboard', 'DashboardController@index');

/****************** Ajax Queries (JSON)**************************************/
Route::get('/getCategories', 'ArtCategoryController@getAllArtCategory');
Route::get('/getPhotos', 'PhotoController@getPhotosByCategoryNArtist');
Route::get('/getArtists', 'PortfolioController@getArtistsByCategoryNArtist');
Route::get('/searchArtistByAlphabet', 'PortfolioController@searchArtistByAlphabet');
Route::get('/getSliderImages', 'SliderController@getSliderImages');
Route::get('/getArtistPhotos', 'PhotoController@getArtistPhotos');
Route::get('/getAllArtists', 'PortfolioController@getAllArtist');
Route::post('/contactus', 'FrontEndController@contactUs');

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);





Route::group(['middleware' => 'admin'], function () {

    /**************** Slider **************************/
    Route::resource('sliders', 'SliderController');

    /**************** Dynamic Contents **************************/
    Route::resource('dynamiccontents', 'DynamicContentController',['except' => 'show']);

    /**************** Album **************************/
    Route::resource('albums', 'AlbumController');


    /**************** Photos ************************/
    Route::resource('photos', 'PhotoController',['except' => 'show']);
    Route::get('photo-album/{albumID}/{page?}', 'PhotoController@getPhotosByAlbum');


    /*************** Portfolios *******************/
    Route::resource('portfolios', 'PortfolioController');
    Route::post('updateProfile', ['as'=>'updateProfile','uses' =>'PortfolioController@updateProfile'] );



    /*************** ArtCategories ***************/
    Route::resource('artcategories', 'ArtCategoryController');


    /*************** Article ************************/
    Route::resource('articles', 'ArticleController',['except' => 'show']);


    /*************** EducationHistory ************************/
    Route::resource('education', 'EducationHistoryController');


    /*************** Awardhistroy ************************/
    Route::resource('awardhistories', 'AwardHistoryController');

    /*************** Exhibition ************************/
    Route::resource('exhibition', 'ExhibitionController');

    /*************** UserController ************************/
    Route::resource('users', 'UserController', ['except' => 'show']);

    Route::get('userstatus/{id}/{status}', 'UserController@changeStatus');


});
Route::resource('dynamiccontents', 'DynamicContentController',['only' => 'show']);
Route::resource('articles', 'ArticleController',['only' => 'show']);
Route::resource('photos', 'PhotoController', ['only' => 'show']);
Route::resource('users', 'UserController', ['only' => 'show']);

app/AwardHistory.php
<?php namespace App;
use Illuminate\Database\Eloquent\Model;
use Auth;
/**
 * Class AwardHistory
 * @package App
 */
class AwardHistory extends Model {

    protected $guarded = [];



    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function portfolio(){
        return $this->belongsTo('App\Portfolio');
    }

    /**
     * @param bool $excludeDeleted
     * @return $this
     */
    public function newQuery($excludeDeleted = true)
    {
        $query = parent::newQuery($excludeDeleted);
        if(Auth::check() && (!Auth::user()->hasRole('admin')))
            return $query->where('portfolio_id', Auth::user()->profile->id);
        else
            return $query;
    }

}

app/Http/Controllers/AwardHistoryController.php
<?php namespace App\Http\Controllers;


use App\Http\Requests;
use App\Portfolio;
use App\Repository\AwardHistoryRepository as AwardHistory;
use App\Http\Requests\CreateAwardHistoryRequest;
use Request;
use Session;

/**
 * Class AwardHistoryController
 * @package App\Http\Controllers
 */
class AwardHistoryController extends Controller
{
    /**
     * @var int
     */
    private $count;

    /*
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

        $this->count = 10;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(AwardHistory $awardHistory)
    {
        $awardhistories = $awardHistory->paginate($this->count);
        return view('admin.awardHistories.index',compact('awardhistories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create(Portfolio $portfolio)
    {
        return view('admin.awardHistories.create')->with('portfolios',$portfolio->all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateAwardHistoryRequest $request
     * @return Response
     */
    public function store(CreateAwardHistoryRequest $request, AwardHistory $awardHistory)
    {

        $awardHistory->create($request->all());
        Session::flash('message', 'The Award History was successfully added!.');
        Session::flash('flash_type', 'alert-success');
        return redirect('awardhistories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id, AwardHistory $awardHistory)
    {
        return view('admin.awardHistories.index')->with('awardhistories', $awardHistory->find($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id, AwardHistory $awardHistory,Portfolio $portfolio)
    {
        return view('admin.awardHistories.edit')->with('awardhistories', $awardHistory->find($id));
    }

    /**
     * @param  int $id
     * @return Response
     */
    public function update($id, CreateAwardHistoryRequest $request, AwardHistory $awardHistory)
    {

        $awardHistory->find($id)->update($request->all());
        Session::flash('message', 'The Award Histories was successfully updated!.');
        Session::flash('flash_type', 'alert-success');
        return redirect('awardhistories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * @param AwardHistory $awardHistory
     * @return mixed
     */
    public function getAllAward(AwardHistory $awardHistory)
    {
        return $awardHistory->all();
    }

}

resources/views/admin/awardHistories/create.blade.php
@extends('admin')

@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Add Award</h3>
    </div>
@stop

@section('adminContent')
    <div class = "article-content">

                        {!! Form::open(['route'=>'awardhistories.store'])!!}

                            <fieldset>
                                 <div class="form-group">
                                     <label><b>TITLE</b></label>
                                     {!! Form::text('title',null,array('class'=>'form-control')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>YEAR</b></label>
                                     {!! Form::text('year',null,array('class'=>'form-control')) !!}
                                 </div>
                                <div class="form-group">
                                  <label>NAME</label>
                                  {!! Form::select('portfolio_id', $portfolioLists) !!}
                                </div>
                                <center>{!! form::submit('Add',[' class'=>'btn btn-primary form-control'])!!}</center>

                            </fieldset>
                        {!! Form::close()!!}

                    </div>

@stop

resources/views/admin/awardHistories/edit.blade.php
@extends('admin')

@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Edit Award History</h3>
    </div>
@stop

@section('adminContent')
    <div class = "portfolio-content">
                        {!! Form::model($awardhistories, array('method' =>'PATCH','route'=>array('awardhistories.update', $awardhistories->id))) !!}

                        <fieldset>
                            <div class="form-group">
                                <label><b>TITLE</b></label>
                                {!! Form::text('title',null,array('class'=>'form-control')) !!}
                            </div>
                            <div class="form-group">
                                <label><b>YEAR</b></label>
                                {!! Form::text('year',null,array('class'=>'form-control')) !!}
                            </div>
                            <div class="form-group">
                              <label>USER</label>
                              {!! Form::select('portfolio_id', $portfolioLists) !!}
                            </div>
                            {!! form::submit('Update',[' class'=>'btn btn-primary form-control'])!!}

                        </fieldset>
                        {!! Form::close()!!}

                    </div>

@stop

resources/views/admin/awardHistories/index.blade.php
@extends('admin')

@section('breadcrumb')
    <h3 class="panel-title">Award History</h3>

    <div class="sub-menu">
        <a href="{{url('awardhistories/create')}}"><i class="fa fa-plus-circle fa-2x pull-right"></i></a>

    </div>
@stop

@section('adminContent')

    <div class="table-responsive award-content">
        <table class="table table-hover table-striped">
            <thead>
            <th> TITLE</th>
            <th> YEAR</th>
            <th> NAME</th>
            <th> ACTIONS</th>
            </thead>

            <tbody>

                @foreach($awardhistories as $awardhistory)
                    <tr>
                    <td>{!! $awardhistory->title !!}</td>
                    <td>{!! $awardhistory->year !!}</td>
                    <td>{!! $awardhistory->portfolio->all()[0]->first_name!!}</td>
                    <td>{!! link_to_route('awardhistories.edit', '', array($awardhistory->id),array('class' => 'fa fa-pencil fa-fw')) !!}</td>
                @endforeach
            </tr>
            </tbody>
        </table>
        <div class="pagination"> {!! $awardhistories->render() !!} </div>
    </div>
@stop