app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/***************    Front End   ***********************/
Route::get('/', 'FrontEndController@index');
Route::get('/home', 'FrontEndController@index');
Route::get('/portfolio', 'FrontEndController@getPortfolio');
Route::get('/news', 'FrontEndController@getNews');
Route::get('/news/{id}', 'FrontEndController@getSingleNews');
Route::get('/artists', 'FrontEndController@getAllArtists');
Route::get('/dashboard', 'DashboardController@index');

/****************** Ajax Queries (JSON)**************************************/
Route::get('/getCategories', 'ArtCategoryController@getAllArtCategory');
Route::get('/getPhotos', 'PhotoController@getPhotosByCategoryNArtist');
Route::get('/getArtists', 'PortfolioController@getArtistsByCategoryNArtist');
Route::get('/searchArtistByAlphabet', 'PortfolioController@searchArtistByAlphabet');
Route::get('/getSliderImages', 'SliderController@getSliderImages');
Route::get('/getArtistPhotos', 'PhotoController@getArtistPhotos');
Route::get('/getAllArtists', 'PortfolioController@getAllArtist');
Route::post('/contactus', 'FrontEndController@contactUs');

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);





Route::group(['middleware' => 'admin'], function () {

    /**************** Slider **************************/
    Route::resource('sliders', 'SliderController');

    /**************** Dynamic Contents **************************/
    Route::resource('dynamiccontents', 'DynamicContentController',['except' => 'show']);

    /**************** Album **************************/
    Route::resource('albums', 'AlbumController');


    /**************** Photos ************************/
    Route::resource('photos', 'PhotoController',['except' => 'show']);
    Route::get('photo-album/{albumID}/{page?}', 'PhotoController@getPhotosByAlbum');


    /*************** Portfolios *******************/
    Route::resource('portfolios', 'PortfolioController');
    Route::post('updateProfile', ['as'=>'updateProfile','uses' =>'PortfolioController@updateProfile'] );



    /*************** ArtCategories ***************/
    Route::resource('artcategories', 'ArtCategoryController');


    /*************** Article ************************/
    Route::resource('articles', 'ArticleController',['except' => 'show']);


    /*************** EducationHistory ************************/
    Route::resource('education', 'EducationHistoryController');


    /*************** Awardhistroy ************************/
    Route::resource('awardhistories', 'AwardHistoryController');

    /*************** Exhibition ************************/
    Route::resource('exhibition', 'ExhibitionController');

    /*************** UserController ************************/
    Route::resource('users', 'UserController', ['except' => 'show']);

    Route::get('userstatus/{id}/{status}', 'UserController@changeStatus');


});
Route::resource('dynamiccontents', 'DynamicContentController',['only' => 'show']);
Route::resource('articles', 'ArticleController',['only' => 'show']);
Route::resource('photos', 'PhotoController', ['only' => 'show']);
Route::resource('users', 'UserController', ['only' => 'show']);

resources/views/admin/dynamics/create.blade.php
@extends('admin')
@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Add Content</h3>
    </div>
@stop
@section('adminContent')
    <div class = "article-content">
        {!! Form::open(['route'=>'dynamiccontents.store','files' => true])!!}

            <fieldset>
                 <div class="form-group">
                     <label><b>TITLE</b></label>
                     {!! Form::text('title',null,array('class'=>'form-control')) !!}
                 </div>
                 <div class="form-group">
                     <label><b>DESCRIPTIOIN</b></label>
                     {!! Form::textarea('description',null,array('class'=>'form-control text-editor')) !!}
                 </div>
                 <div class="form-group">
                     <label><b>STATUS</b></label>
                     {!! Form::select('status', ['Draft'=>'Draft','Published'=> 'Published']) !!}
                 </div>
                 
                   <div class="form-group">
                       <label><b>NAME</b></label>
                      {!! Form::select('user_id', $portfolioLists) !!}
                  </div>

                <center>{!! form::submit('Add',[' class'=>'btn btn-primary form-control'])!!}</center>

            </fieldset>
        {!! Form::close()!!}
        @if($errors->any())
            <ul class="alert alert-danger">
                @foreach($errors->all() as $error)
                   <li> {{ $error }}</li>
                @endforeach
            </ul>
        @endif
    </div>

@stop

resources/views/admin/dynamics/edit.blade.php
@extends('admin')
@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Edit Content</h3>
    </div>
@stop
@section('adminContent')
    <div class = "article-content">
       {!! Form::model($dynamics,array('method' => 'PATCH','route'=>array('dynamiccontents.update',$dynamics->id))) !!}


            <fieldset>
                 <div class="form-group">
                     <label><b>TITLE</b></label>
                     {!! Form::text('title',null,array('class'=>'form-control')) !!}
                 </div>
                 <div class="form-group">
                     <label><b>DESCRIPTIOIN</b></label>
                     {!! Form::textarea('description',null,array('class'=>'form-control text-editor')) !!}
                 </div>
                 <div class="form-group">
                     <label><b>STATUS</b></label>
                     {!! Form::text('status',null,array('class'=>'form-control')) !!}
                 </div>
                 
                   <div class="form-group">
                       <label><b>NAME</b></label>
                      {!! Form::select('user_id', $portfolioLists) !!}
                  </div>

                <center>{!! form::submit('Update',[' class'=>'btn btn-primary form-control'])!!}</center>

            </fieldset>
        {!! Form::close()!!}
        @if($errors->any())
            <ul class="alert alert-danger">
                @foreach($errors->all() as $error)
                   <li> {{ $error }}</li>
                @endforeach
            </ul>
        @endif
    </div>

@stop

resources/views/admin/dynamics/index.blade.php
@extends('admin')

@section('breadcrumb')
    <h3 class="panel-title">Content</h3>
    <div class="sub-menu">
        <a href="{{url('dynamiccontents/create')}}"><i class="fa fa-plus-circle fa-2x pull-right"></i></a>
    </div>
@stop

@section('adminContent')
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
            <th> ID</th>
            <th> TITLE</th>
            <th> STATUS</th>
            <th> USERNAME</th>
            <th> ACTIONS</th>
            </thead>
            <tbody>
               @foreach($dynamics as $dynamic)
                               <tr>
                                   <td>{!! $dynamic->id !!}</a></td>
                                   <td>{!! $dynamic->title !!}</a></td>
                                   <td>{!! $dynamic->status !!}</td>
                                   <td>{!! $dynamic->user->all()[0]->username !!}</td>
                                   <td>{!! link_to_route('dynamiccontents.edit', '', array($dynamic->id),array('class' => 'fa fa-pencil fa-fw')) !!}</td>

               @endforeach
                               </tr>
            </tbody>
        </table>

    </div>
@stop