app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/***************    Front End   ***********************/
Route::get('/', 'FrontEndController@index');
Route::get('/home', 'FrontEndController@index');
Route::get('/portfolio', 'FrontEndController@getPortfolio');
Route::get('/news', 'FrontEndController@getNews');
Route::get('/news/{id}', 'FrontEndController@getSingleNews');
Route::get('/artists', 'FrontEndController@getAllArtists');
Route::get('/dashboard', 'DashboardController@index');

/****************** Ajax Queries (JSON)**************************************/
Route::get('/getCategories', 'ArtCategoryController@getAllArtCategory');
Route::get('/getPhotos', 'PhotoController@getPhotosByCategoryNArtist');
Route::get('/getArtists', 'PortfolioController@getArtistsByCategoryNArtist');
Route::get('/searchArtistByAlphabet', 'PortfolioController@searchArtistByAlphabet');
Route::get('/getSliderImages', 'SliderController@getSliderImages');
Route::get('/getArtistPhotos', 'PhotoController@getArtistPhotos');
Route::get('/getAllArtists', 'PortfolioController@getAllArtist');
Route::post('/contactus', 'FrontEndController@contactUs');

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);





Route::group(['middleware' => 'admin'], function () {

    /**************** Slider **************************/
    Route::resource('sliders', 'SliderController');

    /**************** Dynamic Contents **************************/
    Route::resource('dynamiccontents', 'DynamicContentController',['except' => 'show']);

    /**************** Album **************************/
    Route::resource('albums', 'AlbumController');


    /**************** Photos ************************/
    Route::resource('photos', 'PhotoController',['except' => 'show']);
    Route::get('photo-album/{albumID}/{page?}', 'PhotoController@getPhotosByAlbum');


    /*************** Portfolios *******************/
    Route::resource('portfolios', 'PortfolioController');
    Route::post('updateProfile', ['as'=>'updateProfile','uses' =>'PortfolioController@updateProfile'] );



    /*************** ArtCategories ***************/
    Route::resource('artcategories', 'ArtCategoryController');


    /*************** Article ************************/
    Route::resource('articles', 'ArticleController',['except' => 'show']);


    /*************** EducationHistory ************************/
    Route::resource('education', 'EducationHistoryController');


    /*************** Awardhistroy ************************/
    Route::resource('awardhistories', 'AwardHistoryController');

    /*************** Exhibition ************************/
    Route::resource('exhibition', 'ExhibitionController');

    /*************** UserController ************************/
    Route::resource('users', 'UserController', ['except' => 'show']);

    Route::get('userstatus/{id}/{status}', 'UserController@changeStatus');


});
Route::resource('dynamiccontents', 'DynamicContentController',['only' => 'show']);
Route::resource('articles', 'ArticleController',['only' => 'show']);
Route::resource('photos', 'PhotoController', ['only' => 'show']);
Route::resource('users', 'UserController', ['only' => 'show']);

app/EducationHistory.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;
/**
 * Class EducationHistory
 * @package App
 */
class EducationHistory extends Model {

    /**
     * @var array
     */
    protected $guarded = [];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function portfolio(){
        return $this->belongsTo('App\Portfolio');
    }

    /**
     * @param bool $excludeDeleted
     * @return $this
     */
    public function newQuery($excludeDeleted = true)
    {
        $query = parent::newQuery($excludeDeleted);
        if(Auth::check() && (!Auth::user()->hasRole('admin')))
            return $query->where('portfolio_id', Auth::user()->profile->id);
        else
            return $query;
    }
}

app/Http/Controllers/EducationHistoryController.php
<?php namespace App\Http\Controllers;

use App\Portfolio;
use App\Repository\EducationHistoryRepository as EducationHistory;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateEducationHistoryRequest;
use Illuminate\Contracts\Auth\Guard as Auth;


use Session;

class EducationHistoryController extends Controller
{
    /**
     * @var int
     */
    private $count;

    /*
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

        $this->count = 10;
    }


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(EducationHistory $educationHistory)
    {

        $educations = $educationHistory->paginate($this->count);

        return view('admin.educationHistories.index', compact('educations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Portfolio $portfolio
     * @return Response
     */
    public function create(Portfolio $portfolio)
    {
        return view('admin.educationHistories.create')->with('portfolios', $portfolio->all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateEducationHistoryRequest $request
     * @param EducationHistory $education
     * @return Response
     */
    public function store(CreateEducationHistoryRequest $request, EducationHistory $education)
    {
        $education->create($request->all());
        Session::flash('message', 'The Education was successfully added!.');
        Session::flash('flash_type', 'alert-success');

        return redirect('education');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @param EducationHistory $educationHistory
     * @param Portfolio $portfolio
     * @return Response
     */
    public function edit($id, EducationHistory $educationHistory, Portfolio $portfolio)
    {
        return view('admin.educationHistories.edit')->with('educationHistory', $educationHistory->find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id, CreateEducationHistoryRequest $request, EducationHistory $education)
    {
        $education->find($id)->update($request->all());
        Session::flash('message', 'Your Education history was successfully edited!.');
        Session::flash('flash_type', 'alert-success');

        return redirect('education');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }

    public function getAllEducation(EducationHistory $educationHistory)
    {
        return \response::json($educationHistory->all());
    }
}

resources/views/admin/educationHistories/create.blade.php
@extends('admin')

@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Add Education</h3>
    </div>
@stop

@section('adminContent')
    <div class = "Education-content">

                        {!! Form::open(['route'=>'education.store'])!!}

                            <fieldset>
                                 <div class="form-group">
                                     <label><b>SCHOOL</b></label>
                                     {!! Form::text('school',null,array('class'=>'form-control')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>START DATE</b></label>
                                     {!! Form::text('start_date',null,array('class'=>'form-control date-picker')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>END DATE</b></label>
                                     {!! Form::text('end_date',null,array('class'=>'form-control date-picker')) !!}
                                 </div>
                                <div class="form-group">
                                    <label>USER</label>
                                    {!! Form::select('portfolio_id', $portfolioLists) !!}
                                </div>

                                <center>{!! form::submit('Add',[' class'=>'btn btn-primary form-control'])!!}</center>

                            </fieldset>
                        {!! Form::close()!!}

                    </div>

@stop

resources/views/admin/educationHistories/edit.blade.php
@extends('admin')

@section('breadcrumb')
    <div class = "education-content-header">
        <h3 class="panel-title">Edit Education</h3>
    </div>
@stop

@section('adminContent')
    <div class = "education-content">

                        {!! Form::model($educationHistory,array('method' => 'PATCH','route'=>array('education.update',$educationHistory->id))) !!}

                            <fieldset>
                                 <div class="form-group">
                                     <label><b>SCHOOL</b></label>
                                     {!! Form::text('school',null,array('class'=>'form-control')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>START DATE</b></label>
                                     {!! Form::text('start_date',null,array('class'=>'form-control')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>END DATE</b></label>
                                     {!! Form::text('end_date',null,array('class'=>'form-control')) !!}
                                 </div>
                                <div class="form-group">
                                    <label>USER</label>
                                    {!! Form::select('portfolio_id', $portfolioLists) !!}
                                </div>
                                {!! form::submit('Update',[' class'=>'btn btn-primary form-control'])!!}

                            </fieldset>
                        {!! Form::close()!!}

                    </div>

@stop

resources/views/admin/educationHistories/index.blade.php
@extends('admin')

@section('breadcrumb')
    <h3 class="panel-title">Education</h3>

    <div class="sub-menu">
        <a href="{{url('education/create')}}"><i class="fa fa-plus-circle fa-2x pull-right"></i></a>

    </div>
@stop

@section('adminContent')

    <div class="table-responsive education-content">
        <table class="table table-hover table-striped">
            <thead>
            <th> SCHOOL</th>
            <th> START DATE</th>
            <th> END DATE</th>
            <th> NAME</th>
            <th> ACTIONS</th>
            </thead>

            <tbody>

                @foreach($educations as $education)
                    <tr>
                    <td>{!! $education->school!!}</td>
                    <td>{!! $education->start_date!!}</td>
                    <td>{!! $education->end_date!!}</td>
                    <td>{!! $education->portfolio->all()[0]->first_name!!}</td>
                    <td>{!! link_to_route('education.edit', '', array($education->id),array('class' => 'fa fa-pencil fa-fw')) !!}</td>
                @endforeach
            </tr>
            </tbody>
        </table>
        <div class="pagination"> {!! $educations->render() !!} </div>
    </div>
@stop